#!/bin/bash
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2707_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2708_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2710_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2758_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2762_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2765_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2730_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2732_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2741_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2731_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2737_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2738_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2706_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2715_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2716_R1.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2707_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2708_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2710_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2758_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2762_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2765_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2730_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2732_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2741_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2731_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2737_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2738_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2706_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2715_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
cp /rinnlab/rinngrp/UNICORN/timecourse/FIRRE/rawdata/rnaseq/JR2716_R2.fastq.gz /scratch/Shares/rinnclass/MASTER_CLASS/DATA/
