---
title: "basic_figures"
author: "JR"
date: "2024-07-28"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load data from end of lv 6
```{r}

```



# Volcano Plot
```{r}


library(ggplot2)
ggplot(res_df, aes(x = log2FoldChange, y = -log10(padj), color = (padj < 0.05 & abs(log2FoldChange) > 1))) +
  geom_point() +
  labs(x = "Log2 Fold Change", y = "-Log10 Adjusted P-value", color = "Significant") +
  theme_classic()
```

#MA plot
```{r}

library(ggplot2)
ggplot(res_df, aes(x = baseMean, y = log2FoldChange, color = (padj < 0.05 & abs(log2FoldChange) > 1))) +
  geom_point() +
  labs(x = "Average Expression", y = "Log2 Fold Change", color = "Significant") +
  theme_classic()

```

# Heatmap
```{r}

library(pheatmap)
top_genes <- res_df[order(res_df$padj), ][1:20, ]
pheatmap(log2(counts[top_genes$gene, ] + 1), cluster_rows = FALSE, cluster_cols = FALSE, 
         col = colorRampPalette(c("blue", "white", "red"))(100))

```

# Bar plot
```{r}

library(ggplot2)
top_genes <- res_df[order(res_df$padj), ][1:10, ]
ggplot(top_genes, aes(x = reorder(gene, log2FoldChange), y = log2FoldChange)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(x = "Gene", y = "Log2 Fold Change") +
  theme_classic() +
  coord_flip()

```

# Scatter Plot
```{r}


library(ggplot2)
ggplot(data.frame(TPM = TPM_values), aes(x = TPM)) +
  geom_histogram(binwidth = 1, color = "black", fill = "skyblue") +
  labs(x = "TPM Values", y = "Count") +
  theme_classic()
```

