---
title: "ssh_keys"
author: "JR"
date: "2024-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# SSH Keys : Allow two computers to communicate and know they are friends

GOAL: create an Secure SHell (SSH) Key for our local computer. An SSH key
allows to computers to create a secure connection over the internet -- 
which is not always secure.

Everyone will use the SSH key to connect to GitHub so GitHub can make friends 
with your local computer. 

CU Boulder students will also use this SSH key to connect to our Super Computer (FIJI)

For this lesson we will create an SSH key on MACOSX. If you are using a PC
please see:

Link


Let's get started by seeing what we have in our home directory.
```{bash}

# Navigate to home directory where SSH Keys will be stored
cd ~/

# Check out what's here :
ls -lah

# Let's go into our .ssh folder
cd .ssh

# Looking to see what's there
ls -lah

# If it exists already, you can check out the public key using cat
cat id_rsa.pub

```

Ok so we don't have an SSH key yet - but we see documents called 
authorized keys. That document is to place SSH keys generated elswhere
so your computer can make a connection to another computer you may want
want to connect to.

Let's make an SSH key !

```{bash}

# Make sure you are in ~/.ssh
cd ~/.ssh

# This is what we need to make the ssh key !
ssh-keygen -t rsa

# ALSO THIS WAY TO DIRECTLY CONNECT AND TRANSFER KEY
ssh-copy-id -i ~/.ssh/ed25519 jori2700@fiji.colorado.edu

# just use the default name and no password needed
# Then cat the contents of the public key file (id_rsa.pub) and copy to clipboard.

```
Nice our local computer now has an idnetity or SSH key !

# CU Boulder students:
let's connect to our super computer Fiji.

# Public: 
This is worth noting how to connect to other computer.
This process and file names are fairly similar for a computer connection 
you want to make.

# Everyone:
We will use this ssh key in the "connecting to github lesson" shortly !


# Connecting to Fiji via ssh and making secure connection with SSH key
```{bash}
# First let's connect to Fiji via the ssh BASH command

ssh identikey@fiji.colorado.edu 
# type in identikey password

# Let's go to our home directory into .ssh directory
cd ~/.ssh

# we are looking for a document called "authorized keys"
ls -lah

# Let's paste in our local computer SSH key:
nano authorized_keys

# Paste in the SSH key from your local computer 
# Ctrl-x, y - to exit nano
```
# Nice we have a secure connection - now you don't have to type password !
Let's try this and if it requests a password it didn't work :)

```{bash}

ssh <identikey>@fiji.colorado.edu

```

Excellent - now we don't have to type a password to connect to Fiji.

# Bonus in video: if using iterm2 we can set a profile to make a short cut to connect to fiji
that way we don't have to do ssh identikey@fiji.coloardo.edu either !


