---
title: "00_where_is_our_data"
author: "JR"
date: "2024-03-17"
output: html_document
---

# Congratulations you have successfully run RNAseq from reads to quantification of genes.

But where is all the data? !

You ran the pipeline in a directory that has the .config, .sh and samplesheet in it. In the 
run.sh file there was a next flow flag for an output directory that looked like this:

--outdir /scratch/Shares/rinn/Kit/class_RNASeq/output_dir \

This is the directory where your results are after the --outdir.

Navigate there and you should find these folders:
fastqc: quality control on reads 
multiqc: ** very useful results of data **
pipeline info: ** what processes/versions were run (reproducibility!!) and time/resources **
salmon: information on how our reads mapped to genes
star_salmon: ** Quantification of genes in the .GTF input file ! Lots of good data to analyze **
trim galore: information on how adapters were trimmed and other details

# Using your file transfer program download (or if local open):
/multiqc/multiqc_report.html

There is a whole lab meeting worth of data in there !

All the data for analyses and visualization are in the star_salmon folder.

Soon we will be doing statistical analyses of this data in the star_salmon folder!

#################################################################
Exercise: google Salmon and find out what it does and how it works
#################################################################