---
title: "01_2_R_studio_PRO_considerations_CU_STUDENTS"
author: "JR"
date: "2024-03-17"
output: html_document
---

# For the CU Boulder students we are going to be using R Studio PRO on Fiji-viz.

Which is located here:
https://fiji-viz-3.int.colorado.edu/

Login with your CU identikey and password.

### IMPORTANT : please set your first session parameters.
We needed some special software (Java, XML) versions for our analyses.
But we also share Fiji with lots of people so we don't want to change
versions of core programs that may negatively affect other labs.

OUR AMAZING BIOFRONTIERS IT TEAM solved this problem !
They made us a Sandbox to play in with the right software versions !!

# To use the sanbox we need to do a few things:

#1 Create a .Renviron and .Rprofile in our home directory.
Login via terminal to Fiji in your home directory:
```{bash}

cd ~
nano .Renviron
# Paste in:
PATH=/opt/rh/devtoolset-10/root/bin:/usr/bin:$PATH
# Exit nano

nano .RProfile
# Paste in:
.libPaths("~/R")
# Exit Nano
```

#2 login into : 
https://fiji-viz-3.int.colorado.edu

# IMPORTANT: 
Start a new session with these parameters selected (Must be SANDOBOX!)

RStudio Pro
“Session.Name”
Cluster: Slurm
Resource Profile: Small (4 cpu, 32GB mem) Queue: sandbox

# once session starts please make sure to select R 4.3.1 on top right
This is the version of R we will be using but the default is R 3.6.0
# Be sure to change to R4.3.1.

Once logged in please watch this video for a tour of R Studio (same applies for Studio PRO)
https://youtu.be/2EiXyGBsylY

I hope you enjoy the R studio experience !
